### ISSUE TITLE
couldn't install scDataviz_0.99.64

### ISSUE THREAD

**Issue by guanyuanm** [kevinblighe/cytofNet#13]
* installing *source* package ‘scDataviz’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
sh: line 1: 63741 Killed: 9               R_TESTS= '/Library/Frameworks/R.framework/Resources/bin/R' --no-save --no-restore --no-echo 2>&1 < '/var/folders/_n/qsl26hq51zx86dxgxqxdv7dw0000gn/T//RtmpXZuuFt/filef8f6708d7e4f'
ERROR: lazy loading failed for package ‘scDataviz’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/scDataviz’
Error: Failed to install 'scDataviz' from GitHub:
  (converted from warning) installation of package ‘/var/folders/_n/qsl26hq51zx86dxgxqxdv7dw0000gn/T//RtmpMuTdqk/filef8ab7a3f0e15/scDataviz_0.99.64.tar.gz’ had non-zero exit status

**Comment by kevinblighe** [comment]
Hey, are you running this on Mac? Can you provide some system information. The package is still technically in development, and not tested extensively on Mac.

**Comment by guanyuanm** [comment]
<img width="718" alt="Screen Shot 2020-07-13 at 4 36 15 PM" src="https://user-images.githubusercontent.com/26338111/87364781-5fcfb400-c529-11ea-91f3-059b41fb2d6d.png">

**Comment by kevinblighe** [comment]
This has now been accepted to Bioconductor, so, when it receives its first build on their system, you should be able to install from the instructions here (when the page is built): https://bioconductor.org/packages/scDataviz
This may ultimately resolve this installation issue that you are facing.
