### ISSUE TITLE
I couldn't find where the  full workflow for Seurat-to-scDataviz, please let me know, Thanks! Fan

### ISSUE THREAD

**Issue by bx-labs** [kevinblighe/cytofNet#15]
For a full workflow for Seurat-to-scDataviz, see the GitHub vignette.

**Comment by kevinblighe** [comment]
My apologies for the confusion. This is a new package. There is no lengthy workflow for Seurat-to-scDataviz. You simply have to use the `as.SingleCellExperiment()` command to convert your _Seurat_ object to an object that can be used with _scDataviz_.
