### ISSUE TITLE
data should be scaled for PCA and UMAP ??

### ISSUE THREAD

**Issue by lengfei5** [kevinblighe/cytofNet#22]
Hi there, 

Thank you for this nice package and I have just started my first CyTOF data analysis.
I wanna just clarify if I need to scale the antibody intensities across cells for PCA and UMAP, this sort of dimension reduction. 

Best,
Jingkui

**Comment by kevinblighe** [comment]
Hi Jingkui, how have you imported the data? - was it via `processFCS()`? By default `processFCS()` will transform the data via inverse hyperbolic sine, and then store this in the 'scaled' slot of the SingleCellExperiment object, accessible via `assay(sce, 'scaled')`

Technically, you don't need to further scale the data after this for PCA or UMAP. However, if the PCA bi-plot looks strange, you can apply scaling during PCA via `PCAtools::pca(assay(sce, 'scaled'), scale = TRUE)` (by default, `scale `is set to `FALSE`).

Kevin

**Comment by lengfei5** [comment]
Dear @kevinblighe , 

Thank you for your clarification and it is really helpful. 

Really sorry for the delayed response and I was distracted by some other projects for a long time.

Thanks again. 


Best,
Jingkui
