### ISSUE TITLE
stat convex hull

### ISSUE THREAD

**Issue by nfancy** [kevinblighe/cytofNet#23]
Hi,

Thank you very much for this nice visualisation package. Is there a way to add the cluster borders similar to stat convex hull but more organic? Something similar to this paper here:
https://www.biorxiv.org/content/10.1101/2022.07.07.499139v1.full

Thanks in advance.

Best wishes
Nurun

**Comment by kevinblighe** [comment]
Hi, can you elaborate on the figure to which you are referring? Generally, however, there is no funding or resources to further develop _scDataviz_. Sorry.

**Comment by kevinblighe** [comment]
Please re-open this issue if there is still a question or problem.
